version: "3"
services:
  caddy:
    image: caddy:2.3.0
    restart: unless-stopped
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "caddy_data:/data"
      - "caddy_config:/config"
  owncast:
    build: owncast
    restart: unless-stopped
    networks:
      - backend
    ports:
      # - "8080:8080"
      - "1935:1935"
    volumes:
      - "owncast_data:/app/data"
networks:
  frontend:
  backend:
volumes:
  owncast_data: {}
  caddy_data: {}
  caddy_config: {}
