services:
  owncast:
    build: owncast
    ports:
      - "8080:8080"
      - "19350:19350"
    volumes:
      - "owncast_data:/app/data"
      - type: bind
        source: ./shared
        target: /shared
volumes:
  owncast_data: {}
